version: '3.8'

services:
  bedrock:
    image: itzg/minecraft-bedrock-server
    container_name: minecraft-bedrock
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
    volumes:
      - ./mcdata:/data
    env_file:
      - .env
